callbacks:
  patience: 20
  val_monitor: val_bce_loss
dataset:
  cache_featurizers: true
  cls_type: ms1
  data_folder: /data/rbg/users/klingmin/projects/MS_processing/data_BM/mist/
  dataset: canopus
  dataset_type: default
  fp_names:
  - morgan4096
  magma_aux_loss: true
  magma_modulo: 512
  mol_features: fingerprint
  spec_features: peakformula
  split_filename: inchikey_vanilla.tsv
exp_name: 2025-04-07_21-02
model:
  name: mist
  params:
    embed_instrument: true
    form_embedder: pos-cos
    hidden_size: 256
    iterative_loss_weight: 0.4
    iterative_preds: growing
    loss_fn: bce
    magma_loss_lambda: 8
    no_diffs: true
    num_heads: 8
    pairwise_featurization: true
    peak_attn_layers: 2
    pos_weight: 10
    refine_layers: 4
    set_pooling: cls
    shuffle_train: false
    spectra_dropout: 0.1
project: LS
seed: 17
splitter:
  convergence_threshold: 0.003
  num_batches: 100
  patience: 5
  train_ratio: 0.8
  w_balance: 1.0
  w_gap: 1.0
  w_ratio: 1.0
train_params:
  learning_rate: 0.00077
  lr_decay_frac: 0.9
  n_outer_loops: 500
  name: Adam
  scheduler: false
  train_ratio: 0.8
  weight_decay: 1e-7
train_settings:
  augment_data: false
  batch_size: 512
  num_workers: 4
trainer:
  accelerator: gpu
  devices: 4
  gradient_clip_val: 5
  log_every_n_steps: 5
  max_epochs: 200
